#!/bin/bash
echo "=== Instructions pour corriger le Redirect URI dans Keycloak ==="
echo ""
echo "1. Ouvrez votre navigateur et allez sur: http://localhost:8080/auth"
echo "2. Connectez-vous avec:"
echo "   - Username: admin"
echo "   - Password: admin"
echo "3. Sélectionnez le realm: logistics-realm"
echo "4. Allez dans: Clients → logistics-frontend"
echo "5. Dans l'onglet Settings, trouvez 'Valid Redirect URIs'"
echo "6. Ajoutez ces URIs (une par ligne):"
echo "   http://localhost:8093/oauth2-redirect.html"
echo "   http://localhost:8093/swagger-ui/oauth2-redirect.html"
echo "   http://localhost:8093/swagger-ui.html"
echo "   http://localhost:8093/*"
echo "7. Dans 'Web Origins', ajoutez: http://localhost:8093"
echo "8. Cliquez sur 'Save'"
echo ""
echo "Après cela, testez à nouveau dans Swagger UI!"
